services:
  db:
    image: postgres
    container_name: fintech-db
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    restart: always

  price-bot:
    build: .
    container_name: btc-price-bot
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=eu-west-2
    restart: always
